version: "3.8"
services:
  BogusProvider:
    build: .
    image: bogusprovider-alpine:0.3.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets:ro
      - ${HOME}/LocalHostCertificate/:/https/:ro
    container_name: fake
    ports:
      - 5002:5002